In [1]:
import torch
import timm
import torchvision.transforms as transforms
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, Subset
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from torchvision.datasets import ImageFolder
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os
from tqdm import tqdm
import random
import warnings
##from tqdm import tqdm 
warnings.filterwarnings("ignore")

def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    ##torch.backends.cudnn.deterministic = False
    ##torch.backends.cudnn.benchmark = True
    torch.use_deterministic_algorithms(True, warn_only=True)
    print(f"[INFO] All seeds set to {seed}")

seed_everything(42)

def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

g = torch.Generator()
g.manual_seed(42)

# Configuration
##DATA_DIR = "/kaggle/input/mapsimgtxt/spammultimodal"  # Update with dataset path
DATA_DIR = "/kaggle/input/ekafnewsforkhawla/sorted_imagesOur" 

BATCH_SIZE = 8
EPOCHS = 3
LR = 2e-5
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Define models with specific input sizes      
MODELS = {"vit_base_patch32_224": (224, 224),    
          "deit_tiny_patch16_224.fb_in1k": (224, 224),    
          "beit_base_patch16_224.in22k_ft_in22k": (224, 224),    
          "cait_xxs24_224.fb_dist_in1k": (224, 224),
          "timm/crossvit_18_dagger_408.in1k": (408, 408)
}

# Load dataset
dataset = ImageFolder(DATA_DIR)
num_classes = len(dataset.classes)
labels = [sample[1] for sample in dataset.samples]  # Extract labels properly
kf = StratifiedKFold(n_splits=5, shuffle=False, random_state=None)

def free_gpu_memory():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

def train_model(model_name, input_size):
    print(f"Training {model_name}...")
    
    # Free GPU memory before starting a new model
    
    
    # Define data transformations
    transform = transforms.Compose([
        transforms.Resize(input_size),
        transforms.ToTensor()
    ])
    dataset.transform = transform  # Apply transformation to dataset
    
        
    all_preds1, all_labels1 = [], []  # Accumulate results across folds
    
    for fold, (train_idx, val_idx) in enumerate(kf.split(dataset.samples, dataset.targets)):
        free_gpu_memory()
        model = timm.create_model(model_name, pretrained=True, num_classes=num_classes).to(DEVICE)
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.AdamW(model.parameters(), lr=LR)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=2)        
        print(f"Fold {fold+1}/5")
        train_subsampler = Subset(dataset, train_idx)
        val_subsampler = Subset(dataset, val_idx)
        
        train_loader = DataLoader(train_subsampler, batch_size=BATCH_SIZE,generator=g, shuffle=True)
        val_loader = DataLoader(val_subsampler, batch_size=BATCH_SIZE, generator=g,shuffle=False)
        
        for epoch in range(EPOCHS):
            model.train()
            running_loss, correct, total = 0.0, 0, 0
            progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=False)
            
            for images, labels in progress_bar:
                images, labels = images.to(DEVICE), labels.to(DEVICE)
                optimizer.zero_grad()
                outputs = model(images)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()
                running_loss += loss.item()
                _, predicted = torch.max(outputs, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()
                progress_bar.set_postfix(loss=running_loss / len(train_loader), acc=100 * correct / total)
            
            print(f"Epoch {epoch+1}, Loss: {running_loss / len(train_loader):.4f}, Accuracy: {100 * correct / total:.2f}%")
            scheduler.step(running_loss / len(train_loader))
        
        # Validation
        model.eval()
        all_preds, all_labels = [], []
        with torch.no_grad():
            for images, labels in tqdm(val_loader, desc="Validating", leave=False):
                images, labels = images.to(DEVICE), labels.to(DEVICE)
                outputs = model(images)
                _, preds = torch.max(outputs, 1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())
                all_preds1.extend(preds.cpu().numpy())
                all_labels1.extend(labels.cpu().numpy())
            
        print(f"Fold {fold+1} Accuracy: {accuracy_score(all_labels, all_preds):.4f}")
        print(classification_report(all_labels, all_preds, digits=4, zero_division=0))  
        print(confusion_matrix(all_labels, all_preds))
    
    print(f"\n✅✅✅✅✅✅✅✅✅✅✅ {model_name}✅✅✅✅✅✅✅✅✅✅✅✅✅")
    print(classification_report(all_labels1, all_preds1, digits=4, zero_division=0))  
    print(confusion_matrix(all_labels1, all_preds1))
    print(f"\n✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅")

# Train each model with corresponding input size
for model_name, input_size in MODELS.items():
    train_model(model_name, input_size)


/usr/local/lib/python3.12/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` 

[INFO] All seeds set to 42
Training vit_base_patch32_224...


model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Fold 1/5


Epoch 1, Loss: 0.5391, Accuracy: 74.40%


Epoch 2, Loss: 0.3506, Accuracy: 85.18%


Epoch 3, Loss: 0.1046, Accuracy: 96.35%


Fold 1 Accuracy: 0.6936
              precision    recall  f1-score   support

           0     0.4393    0.5568    0.4911       273
           1     0.8226    0.7430    0.7808       755

    accuracy                         0.6936      1028
   macro avg     0.6309    0.6499    0.6360      1028
weighted avg     0.7208    0.6936    0.7039      1028

[[152 121]
 [194 561]]
Fold 2/5


Epoch 1, Loss: 0.5171, Accuracy: 76.06%


Epoch 2, Loss: 0.2565, Accuracy: 89.54%


Epoch 3, Loss: 0.0617, Accuracy: 98.18%


Fold 2 Accuracy: 0.6839
              precision    recall  f1-score   support

           0     0.3863    0.3309    0.3564       272
           1     0.7711    0.8108    0.7905       756

    accuracy                         0.6839      1028
   macro avg     0.5787    0.5709    0.5734      1028
weighted avg     0.6693    0.6839    0.6756      1028

[[ 90 182]
 [143 613]]
Fold 3/5


Epoch 1, Loss: 0.5126, Accuracy: 76.20%


Epoch 2, Loss: 0.2411, Accuracy: 90.05%


Epoch 3, Loss: 0.0553, Accuracy: 98.52%


Fold 3 Accuracy: 0.7383
              precision    recall  f1-score   support

           0     0.5319    0.0919    0.1567       272
           1     0.7482    0.9709    0.8451       756

    accuracy                         0.7383      1028
   macro avg     0.6401    0.5314    0.5009      1028
weighted avg     0.6910    0.7383    0.6630      1028

[[ 25 247]
 [ 22 734]]
Fold 4/5


Epoch 1, Loss: 0.5114, Accuracy: 76.82%


Epoch 2, Loss: 0.2481, Accuracy: 89.61%


Epoch 3, Loss: 0.0675, Accuracy: 98.10%


Fold 4 Accuracy: 0.7020
              precision    recall  f1-score   support

           0     0.3910    0.2243    0.2850       272
           1     0.7577    0.8742    0.8118       755

    accuracy                         0.7020      1027
   macro avg     0.5744    0.5492    0.5484      1027
weighted avg     0.6606    0.7020    0.6723      1027

[[ 61 211]
 [ 95 660]]
Fold 5/5


Epoch 1, Loss: 0.5152, Accuracy: 76.21%


Epoch 2, Loss: 0.2657, Accuracy: 89.30%


Epoch 3, Loss: 0.0706, Accuracy: 98.22%


Fold 5 Accuracy: 0.7196
              precision    recall  f1-score   support

           0     0.3824    0.0956    0.1529       272
           1     0.7435    0.9444    0.8320       755

    accuracy                         0.7196      1027
   macro avg     0.5629    0.5200    0.4925      1027
weighted avg     0.6478    0.7196    0.6521      1027

[[ 26 246]
 [ 42 713]]

✅✅✅✅✅✅✅✅✅✅✅ vit_base_patch32_224✅✅✅✅✅✅✅✅✅✅✅✅✅
              precision    recall  f1-score   support

           0     0.4165    0.2601    0.3202      1361
           1     0.7652    0.8687    0.8136      3777

    accuracy                         0.7075      5138
   macro avg     0.5908    0.5644    0.5669      5138
weighted avg     0.6728    0.7075    0.6829      5138

[[ 354 1007]
 [ 496 3281]]

✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
Training deit_tiny_patch16_224.fb_in1k...


model.safetensors:   0%|          | 0.00/22.9M [00:00<?, ?B/s]

Fold 1/5


Epoch 1, Loss: 0.5474, Accuracy: 74.45%


Epoch 2, Loss: 0.4201, Accuracy: 81.27%


Epoch 3, Loss: 0.2210, Accuracy: 92.26%


Fold 1 Accuracy: 0.6877
              precision    recall  f1-score   support

           0     0.4000    0.3516    0.3743       273
           1     0.7754    0.8093    0.7920       755

    accuracy                         0.6877      1028
   macro avg     0.5877    0.5805    0.5831      1028
weighted avg     0.6757    0.6877    0.6810      1028

[[ 96 177]
 [144 611]]
Fold 2/5


Epoch 1, Loss: 0.5383, Accuracy: 74.33%


Epoch 2, Loss: 0.3825, Accuracy: 82.51%


Epoch 3, Loss: 0.1913, Accuracy: 93.38%


Fold 2 Accuracy: 0.6761
              precision    recall  f1-score   support

           0     0.3467    0.2537    0.2930       272
           1     0.7551    0.8280    0.7899       756

    accuracy                         0.6761      1028
   macro avg     0.5509    0.5409    0.5414      1028
weighted avg     0.6471    0.6761    0.6584      1028

[[ 69 203]
 [130 626]]
Fold 3/5


Epoch 1, Loss: 0.5317, Accuracy: 75.16%


Epoch 2, Loss: 0.3666, Accuracy: 83.48%


Epoch 3, Loss: 0.1778, Accuracy: 93.80%


Fold 3 Accuracy: 0.7082
              precision    recall  f1-score   support

           0     0.3814    0.1654    0.2308       272
           1     0.7505    0.9034    0.8199       756

    accuracy                         0.7082      1028
   macro avg     0.5660    0.5344    0.5253      1028
weighted avg     0.6529    0.7082    0.6640      1028

[[ 45 227]
 [ 73 683]]
Fold 4/5


Epoch 1, Loss: 0.5303, Accuracy: 75.14%


Epoch 2, Loss: 0.3650, Accuracy: 84.68%


Epoch 3, Loss: 0.1665, Accuracy: 95.14%


Fold 4 Accuracy: 0.6806
              precision    recall  f1-score   support

           0     0.3272    0.1949    0.2442       272
           1     0.7468    0.8556    0.7975       755

    accuracy                         0.6806      1027
   macro avg     0.5370    0.5252    0.5209      1027
weighted avg     0.6357    0.6806    0.6510      1027

[[ 53 219]
 [109 646]]
Fold 5/5


Epoch 1, Loss: 0.5362, Accuracy: 74.95%


Epoch 2, Loss: 0.4041, Accuracy: 82.92%


Epoch 3, Loss: 0.2067, Accuracy: 92.61%


Fold 5 Accuracy: 0.7089
              precision    recall  f1-score   support

           0     0.4151    0.2426    0.3063       272
           1     0.7627    0.8768    0.8158       755

    accuracy                         0.7089      1027
   macro avg     0.5889    0.5597    0.5610      1027
weighted avg     0.6706    0.7089    0.6808      1027

[[ 66 206]
 [ 93 662]]

✅✅✅✅✅✅✅✅✅✅✅ deit_tiny_patch16_224.fb_in1k✅✅✅✅✅✅✅✅✅✅✅✅✅
              precision    recall  f1-score   support

           0     0.3747    0.2417    0.2939      1361
           1     0.7577    0.8546    0.8033      3777

    accuracy                         0.6923      5138
   macro avg     0.5662    0.5482    0.5486      5138
weighted avg     0.6563    0.6923    0.6683      5138

[[ 329 1032]
 [ 549 3228]]

✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
Training beit_base_patch16_224.in22k_ft_in22k...


model.safetensors:   0%|          | 0.00/414M [00:00<?, ?B/s]

Fold 1/5


Epoch 1, Loss: 0.5849, Accuracy: 73.45%


Epoch 2, Loss: 0.5795, Accuracy: 73.53%


Epoch 3, Loss: 0.5533, Accuracy: 74.48%


Fold 1 Accuracy: 0.7335
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000       273
           1     0.7342    0.9987    0.8462       755

    accuracy                         0.7335      1028
   macro avg     0.3671    0.4993    0.4231      1028
weighted avg     0.5392    0.7335    0.6215      1028

[[  0 273]
 [  1 754]]
Fold 2/5


Epoch 1, Loss: 0.5734, Accuracy: 73.58%


Epoch 2, Loss: 0.4638, Accuracy: 78.59%


Epoch 3, Loss: 0.2592, Accuracy: 89.83%


Fold 2 Accuracy: 0.6459
              precision    recall  f1-score   support

           0     0.3403    0.3603    0.3500       272
           1     0.7649    0.7487    0.7567       756

    accuracy                         0.6459      1028
   macro avg     0.5526    0.5545    0.5533      1028
weighted avg     0.6525    0.6459    0.6491      1028

[[ 98 174]
 [190 566]]
Fold 3/5


Epoch 1, Loss: 0.5781, Accuracy: 73.50%


Epoch 2, Loss: 0.4826, Accuracy: 77.54%


Epoch 3, Loss: 0.3035, Accuracy: 87.64%


Fold 3 Accuracy: 0.7130
              precision    recall  f1-score   support

           0     0.2909    0.0588    0.0979       272
           1     0.7369    0.9484    0.8294       756

    accuracy                         0.7130      1028
   macro avg     0.5139    0.5036    0.4636      1028
weighted avg     0.6189    0.7130    0.6358      1028

[[ 16 256]
 [ 39 717]]
Fold 4/5


Epoch 1, Loss: 0.5674, Accuracy: 73.63%


Epoch 2, Loss: 0.4536, Accuracy: 78.96%


Epoch 3, Loss: 0.2436, Accuracy: 90.68%


Fold 4 Accuracy: 0.7176
              precision    recall  f1-score   support

           0     0.4274    0.1949    0.2677       272
           1     0.7575    0.9060    0.8251       755

    accuracy                         0.7176      1027
   macro avg     0.5924    0.5504    0.5464      1027
weighted avg     0.6701    0.7176    0.6775      1027

[[ 53 219]
 [ 71 684]]
Fold 5/5


Epoch 1, Loss: 0.5818, Accuracy: 73.51%


Epoch 2, Loss: 0.5329, Accuracy: 75.58%


Epoch 3, Loss: 0.3992, Accuracy: 82.90%


Fold 5 Accuracy: 0.6738
              precision    recall  f1-score   support

           0     0.2797    0.1471    0.1928       272
           1     0.7376    0.8636    0.7956       755

    accuracy                         0.6738      1027
   macro avg     0.5086    0.5053    0.4942      1027
weighted avg     0.6163    0.6738    0.6359      1027

[[ 40 232]
 [103 652]]

✅✅✅✅✅✅✅✅✅✅✅ beit_base_patch16_224.in22k_ft_in22k✅✅✅✅✅✅✅✅✅✅✅✅✅
              precision    recall  f1-score   support

           0     0.3388    0.1521    0.2099      1361
           1     0.7451    0.8930    0.8124      3777

    accuracy                         0.6968      5138
   macro avg     0.5419    0.5226    0.5112      5138
weighted avg     0.6375    0.6968    0.6528      5138

[[ 207 1154]
 [ 404 3373]]

✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
Training cait_xxs24_224.fb_dist_in1k...


model.safetensors:   0%|          | 0.00/47.9M [00:00<?, ?B/s]

Fold 1/5


Epoch 1, Loss: 0.5563, Accuracy: 74.21%


Epoch 2, Loss: 0.3900, Accuracy: 82.43%


Epoch 3, Loss: 0.1830, Accuracy: 93.53%


Fold 1 Accuracy: 0.6907
              precision    recall  f1-score   support

           0     0.3636    0.2198    0.2740       273
           1     0.7532    0.8609    0.8035       755

    accuracy                         0.6907      1028
   macro avg     0.5584    0.5404    0.5387      1028
weighted avg     0.6497    0.6907    0.6628      1028

[[ 60 213]
 [105 650]]
Fold 2/5


Epoch 1, Loss: 0.5438, Accuracy: 74.77%


Epoch 2, Loss: 0.3751, Accuracy: 83.36%


Epoch 3, Loss: 0.1741, Accuracy: 94.31%


Fold 2 Accuracy: 0.6702
              precision    recall  f1-score   support

           0     0.3169    0.2132    0.2549       272
           1     0.7467    0.8347    0.7883       756

    accuracy                         0.6702      1028
   macro avg     0.5318    0.5239    0.5216      1028
weighted avg     0.6330    0.6702    0.6471      1028

[[ 58 214]
 [125 631]]
Fold 3/5


Epoch 1, Loss: 0.5334, Accuracy: 75.11%


Epoch 2, Loss: 0.3692, Accuracy: 83.63%


Epoch 3, Loss: 0.1566, Accuracy: 94.74%


Fold 3 Accuracy: 0.7160
              precision    recall  f1-score   support

           0     0.4194    0.1912    0.2626       272
           1     0.7566    0.9048    0.8241       756

    accuracy                         0.7160      1028
   macro avg     0.5880    0.5480    0.5434      1028
weighted avg     0.6674    0.7160    0.6755      1028

[[ 52 220]
 [ 72 684]]
Fold 4/5


Epoch 1, Loss: 0.5316, Accuracy: 75.94%


Epoch 2, Loss: 0.3471, Accuracy: 85.31%


Epoch 3, Loss: 0.1391, Accuracy: 95.23%


Fold 4 Accuracy: 0.6056
              precision    recall  f1-score   support

           0     0.3290    0.4706    0.3873       272
           1     0.7743    0.6543    0.7093       755

    accuracy                         0.6056      1027
   macro avg     0.5517    0.5624    0.5483      1027
weighted avg     0.6564    0.6056    0.6240      1027

[[128 144]
 [261 494]]
Fold 5/5


Epoch 1, Loss: 0.5403, Accuracy: 75.72%


Epoch 2, Loss: 0.3827, Accuracy: 83.58%


Epoch 3, Loss: 0.1784, Accuracy: 93.97%


Fold 5 Accuracy: 0.6670
              precision    recall  f1-score   support

           0     0.2727    0.1544    0.1972       272
           1     0.7365    0.8517    0.7899       755

    accuracy                         0.6670      1027
   macro avg     0.5046    0.5030    0.4936      1027
weighted avg     0.6137    0.6670    0.6329      1027

[[ 42 230]
 [112 643]]

✅✅✅✅✅✅✅✅✅✅✅ cait_xxs24_224.fb_dist_in1k✅✅✅✅✅✅✅✅✅✅✅✅✅
              precision    recall  f1-score   support

           0     0.3350    0.2498    0.2862      1361
           1     0.7524    0.8213    0.7853      3777

    accuracy                         0.6699      5138
   macro avg     0.5437    0.5356    0.5358      5138
weighted avg     0.6418    0.6699    0.6531      5138

[[ 340 1021]
 [ 675 3102]]

✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
Training timm/crossvit_18_dagger_408.in1k...


model.safetensors:   0%|          | 0.00/178M [00:00<?, ?B/s]

Fold 1/5


Epoch 1, Loss: 0.5497, Accuracy: 74.40%


Epoch 2, Loss: 0.4207, Accuracy: 80.78%


Epoch 3, Loss: 0.2364, Accuracy: 91.34%


Fold 1 Accuracy: 0.7344
              precision    recall  f1-score   support

           0     0.5000    0.2784    0.3576       273
           1     0.7751    0.8993    0.8326       755

    accuracy                         0.7344      1028
   macro avg     0.6376    0.5889    0.5951      1028
weighted avg     0.7021    0.7344    0.7065      1028

[[ 76 197]
 [ 76 679]]
Fold 2/5


Epoch 1, Loss: 0.5290, Accuracy: 74.70%


Epoch 2, Loss: 0.3654, Accuracy: 84.74%


Epoch 3, Loss: 0.1734, Accuracy: 94.26%


Fold 2 Accuracy: 0.6060
              precision    recall  f1-score   support

           0     0.2805    0.3125    0.2957       272
           1     0.7421    0.7116    0.7265       756

    accuracy                         0.6060      1028
   macro avg     0.5113    0.5121    0.5111      1028
weighted avg     0.6199    0.6060    0.6125      1028

[[ 85 187]
 [218 538]]
Fold 3/5


Epoch 1, Loss: 0.5355, Accuracy: 75.21%


Epoch 2, Loss: 0.3917, Accuracy: 83.16%


Epoch 3, Loss: 0.2123, Accuracy: 92.02%


Fold 3 Accuracy: 0.6897
              precision    recall  f1-score   support

           0     0.3819    0.2794    0.3227       272
           1     0.7636    0.8373    0.7987       756

    accuracy                         0.6897      1028
   macro avg     0.5727    0.5584    0.5607      1028
weighted avg     0.6626    0.6897    0.6728      1028

[[ 76 196]
 [123 633]]
Fold 4/5


Epoch 1, Loss: 0.5319, Accuracy: 74.92%


Epoch 2, Loss: 0.3812, Accuracy: 83.26%


Epoch 3, Loss: 0.1986, Accuracy: 92.85%


Fold 4 Accuracy: 0.7098
              precision    recall  f1-score   support

           0     0.3984    0.1875    0.2550       272
           1     0.7542    0.8980    0.8198       755

    accuracy                         0.7098      1027
   macro avg     0.5763    0.5428    0.5374      1027
weighted avg     0.6600    0.7098    0.6702      1027

[[ 51 221]
 [ 77 678]]
Fold 5/5


Epoch 1, Loss: 0.5401, Accuracy: 74.87%


Epoch 2, Loss: 0.3922, Accuracy: 83.22%


Epoch 3, Loss: 0.2071, Accuracy: 92.58%


Fold 5 Accuracy: 0.6650
              precision    recall  f1-score   support

           0     0.3000    0.1985    0.2389       272
           1     0.7426    0.8331    0.7853       755

    accuracy                         0.6650      1027
   macro avg     0.5213    0.5158    0.5121      1027
weighted avg     0.6254    0.6650    0.6406      1027

[[ 54 218]
 [126 629]]

✅✅✅✅✅✅✅✅✅✅✅ timm/crossvit_18_dagger_408.in1k✅✅✅✅✅✅✅✅✅✅✅✅✅
              precision    recall  f1-score   support

           0     0.3555    0.2513    0.2944      1361
           1     0.7560    0.8358    0.7939      3777

    accuracy                         0.6810      5138
   macro avg     0.5557    0.5436    0.5442      5138
weighted avg     0.6499    0.6810    0.6616      5138

[[ 342 1019]
 [ 620 3157]]

✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
